version: '3.8'

services:
  e_morgue_api:
    image: drepl/e_morgue_api:latest
    container_name: e_morgue_api
    ports:
      - "3000:3000" 
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongoadmin:passer@mongodb:27017/e_morgue_db
    networks:
      - app-network

  e_morgue_fe:
    image: drepl/e_morgue_fe:latest
    container_name: e_morgue_fe
    ports:
      - "8080:80"
    depends_on:
      - e_morgue_api
    networks:
      - app-network


  mongodb:
    image: mongo:latest 
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: passer
    volumes:
      - mongodb_data:/data/db 
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb  
      ME_CONFIG_MONGODB_PORT: 27017     
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin  # Utilisateur admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: passer  # Mot de passe admin
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:passer@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - app-network


networks:
  app-network:
    driver: bridge


volumes:
  mongodb_data:
    driver: local
